DROP DATABASE IF EXISTS movie_db;
CREATE DATABASE movie_db;

USE movie_db;

CREATE TABLE movie (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    moive_name VARCHAR(100) NOT NULL
);

CREATE TABLE movie_reviews (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    moive_id INT NOT NULL,
    review_id TEXT NOT NULL
);

